services:
  - type: web
    name: image-store-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        sync: false  # Set this in Render dashboard
      - key: DB_HOST
        sync: false  # Set this in Render dashboard
      - key: DB_PORT
        value: 5432
